########################################################################################
# "bun install" composite action                                                       #
#--------------------------------------------------------------------------------------#
# Cache:                                                                               #
#   - Downloaded packages cache                                                        #
#   - node_modules directory                                                           #
########################################################################################

name: 'Bun install'
description: 'Run bun install with cache enabled'
inputs:
  node_version:
    description: 'Node.js version to use'
    required: false
    default: v20.x

runs:
  using: 'composite'
  steps:
    - name: Use Node ${{ inputs.node_version }}
      uses: buildjet/setup-node@v4
      with:
        node-version: ${{ inputs.node_version }}

    - name: Install Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    # Cache bun's package cache
    - name: Restore Bun cache
      uses: buildjet/cache@v4
      id: bun-cache
      with:
        path: ~/.bun/install/cache
        key: bun-cache-${{ hashFiles('bun.lockb', 'package.json') }}
        restore-keys: bun-cache-

    # Cache node_modules
    - name: Restore node_modules
      id: bun-nm-cache
      uses: buildjet/cache@v4
      with:
        path: '**/node_modules/'
        key: ${{ runner.os }}-bun-nm-cache-${{ hashFiles('bun.lockb', 'package.json') }}

    - name: Install dependencies
      shell: bash
      run: |
        bun install
        bun prisma generate
