#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

export NVM_DIR="$HOME/.nvm"
. "$NVM_DIR/nvm.sh"

export PATH=$PATH:$HOME/.nvm/versions/node/$(nvm current)/bin

npx --version

npx commitlint --edit $1
