#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

branch_name=$(git symbolic-ref --short HEAD)
pattern="^(claudio|mariano|alex)/leap-.*$"

if [[ ! $branch_name =~ $pattern ]]; then
  echo "Branch name '$branch_name' does not follow the naming convention."
  exit 1
fi