#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

export NVM_DIR="$HOME/.nvm"
. "$NVM_DIR/nvm.sh"

export PATH=$PATH:$HOME/.nvm/versions/node/$(nvm current)/bin:$HOME/.bun/bin


echo Node version: $(node -v)
echo Bun version: $(bun -v)

bun run test
